version: 2

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 1
    versioning-strategy: increase
    reviewers:
      - nandordudas
    commit-message:
      prefix: chore(deps)
      include: scope
