name: Cleanup caches by a branch

permissions:
  actions: write

on:
  pull_request:
    types:
      - closed
  workflow_dispatch: {}

jobs:
  cleanup:
    timeout-minutes: 5
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Clear cache
        uses: actions/github-script@v6
        with:
          script: |
            const { payload, repo: { owner, repo } } = context
            const pullRequestNumber = payload?.pull_request?.number
            const ref = pullRequestNumber ? `refs/pull/${pullRequestNumber}/merge` : undefined
            const caches = await github.rest.actions.getActionsCacheList({ owner, ref, repo })
            let shouldCheckMainCache = true

            await Promise.allSettled(caches.data.actions_caches.map(({ id: cache_id, ref }) => {
              if (shouldCheckMainCache && ref === 'refs/heads/main') {
                shouldCheckMainCache = false

                return
              }

              return github.rest.actions.deleteActionsCacheById({ cache_id, owner, repo })
            })).then(console.log)
